// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzglwebnxynjkiqpquay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6Z2x3ZWJueHluamtpcXBxdWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTcxODIsImV4cCI6MjA2NDY5MzE4Mn0.yjp_Ps3tyVuNDTIiL98lAEDUHGys9DXkkW1LUZh88DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);